name: Deploy Lambda

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Py Lambda Deploy
        uses: mariamrf/py-lambda-action@v0.0.2
        secrets:
          - "AWS_ACCESS_KEY_ID"
          - "AWS_SECRET_ACCESS_KEY"
          - "AWS_DEFAULT_REGION"
          - "LAMBDA_FUNCTION_NAME"
          - "LAMBDA_LAYER_ARN"
